#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PY="${PY:-/home/hp/anaconda3/envs/LMAC/bin/python}"
STAMP="${STAMP:-$(date -u +%Y%m%d_%H%M%S)}"
OUT_ROOT="${OUT_ROOT:-$ROOT/description/certification_gate/drc_two_stage_evidence_$STAMP}"

RUN_MODE="${RUN_MODE:-dry_run}"  # dry_run | split | execute
COLLECT_BUFFERS="${COLLECT_BUFFERS:-false}"
RUN_MAPS="${RUN_MAPS:-1o_10b_vs_1r 1o_2r_vs_4r 5z_vs_1ul}"
COLLECT_MAPS="${COLLECT_MAPS:-10b 2r 5z}"
CANDIDATE_ROOT="${CANDIDATE_ROOT:-$ROOT/src/llm_source/LMAC_deepseek-v4-flash_MSE_0.05}"
CANDIDATE_MANIFEST="${CANDIDATE_MANIFEST:-$OUT_ROOT/drc_candidates.json}"
CANDIDATE_MANIFEST_MD="${CANDIDATE_MANIFEST_MD:-$OUT_ROOT/drc_candidates.md}"
BUFFER_ROOT="${BUFFER_ROOT:-$OUT_ROOT/formal_buffers}"
SPLIT_ROOT="${SPLIT_ROOT:-$OUT_ROOT/buffer_split}"
CALIBRATION_ROOT="${CALIBRATION_ROOT:-$SPLIT_ROOT/calibration}"
CERTIFICATION_ROOT="${CERTIFICATION_ROOT:-$SPLIT_ROOT/certification}"
CALIBRATION_OUT="${CALIBRATION_OUT:-$OUT_ROOT/calibration_drc}"
FACT_SUBSET_MANIFEST="${FACT_SUBSET_MANIFEST:-$OUT_ROOT/drc_fact_subset_manifest.json}"
FACT_SUBSET_MANIFEST_MD="${FACT_SUBSET_MANIFEST_MD:-$OUT_ROOT/drc_fact_subset_manifest.md}"
CERTIFICATION_OUT="${CERTIFICATION_OUT:-$OUT_ROOT/certification_drc}"
PROMPT_DIR="${PROMPT_DIR:-$OUT_ROOT/candidate_prompts}"

TRAIN_COUNT="${TRAIN_COUNT:-64}"
TEST_COUNT="${TEST_COUNT:-64}"
SEED="${SEED:-1234}"
COLLECT_CHUNK_SIZE="${COLLECT_CHUNK_SIZE:-0}"
OVERWRITE_OUTPUT="${OVERWRITE_OUTPUT:-false}"

AUDIT_MAX_FILES="${AUDIT_MAX_FILES:-64}"
MAX_FILES="${MAX_FILES:-64}"
MAX_TRANSITIONS="${MAX_TRANSITIONS:-4096}"
PROBE_MODEL="${PROBE_MODEL:-mlp}"
PROBE_HIDDEN_DIM="${PROBE_HIDDEN_DIM:-128}"
PROBE_WEIGHT_DECAY="${PROBE_WEIGHT_DECAY:-0.0001}"
PROBE_EPOCHS="${PROBE_EPOCHS:-120}"
DECISION_ORACLE="${DECISION_ORACLE:-auto}"
DECISION_LABEL="${DECISION_LABEL:-raw_action}"
MIN_CONDITIONAL_DECISION_NATS="${MIN_CONDITIONAL_DECISION_NATS:-0.01}"
CONDITIONAL_DECISION_MODE="${CONDITIONAL_DECISION_MODE:-none}"
CONDITIONAL_DECISION_QUANTILE="${CONDITIONAL_DECISION_QUANTILE:-0.25}"
MIN_CONDITIONAL_DECISION_SAMPLES="${MIN_CONDITIONAL_DECISION_SAMPLES:-256}"
MIN_RECEIVER_NECESSITY_RATE="${MIN_RECEIVER_NECESSITY_RATE:-1.0}"
SCORE_GAIN_CAP="${SCORE_GAIN_CAP:-1.0}"
N_BOOTSTRAP="${N_BOOTSTRAP:-500}"
N_SIGN_PERMUTATIONS="${N_SIGN_PERMUTATIONS:-500}"
N_MESSAGE_SHUFFLES="${N_MESSAGE_SHUFFLES:-16}"
STAT_ALPHA="${STAT_ALPHA:-0.05}"
REQUIRE_STAT_SIGNIFICANCE="${REQUIRE_STAT_SIGNIFICANCE:-true}"
REQUIRE_CONTENT_CONTROL="${REQUIRE_CONTENT_CONTROL:-true}"

mkdir -p "$OUT_ROOT"

cat > "$OUT_ROOT/README.md" <<EOF
# DRC Two-Stage Evidence Pipeline

- stamp: \`$STAMP\`
- run mode: \`$RUN_MODE\`
- collect buffers: \`$COLLECT_BUFFERS\`
- collect chunk size: \`$COLLECT_CHUNK_SIZE\`
- maps: \`$RUN_MAPS\`
- collect aliases: \`$COLLECT_MAPS\`
- candidate root: \`$CANDIDATE_ROOT\`
- candidate manifest: \`$CANDIDATE_MANIFEST\`
- buffer root: \`$BUFFER_ROOT\`
- split root: \`$SPLIT_ROOT\`
- calibration root: \`$CALIBRATION_ROOT\`
- certification root: \`$CERTIFICATION_ROOT\`
- calibration DRC: \`$CALIBRATION_OUT\`
- fact subset manifest: \`$FACT_SUBSET_MANIFEST\`
- certification DRC: \`$CERTIFICATION_OUT\`
- decision label: \`$DECISION_LABEL\`
- conditional decision mode: \`$CONDITIONAL_DECISION_MODE\`
- conditional decision quantile: \`$CONDITIONAL_DECISION_QUANTILE\`
- min conditional decision samples: \`$MIN_CONDITIONAL_DECISION_SAMPLES\`

## Protocol

1. Freeze candidate manifest.
2. Optionally collect formal train/test buffers.
3. Split train/test buffers into calibration/certification roots.
4. Run calibration DRC on calibration root.
5. Derive receiver-necessity fact subset from calibration DRC.
6. Run final certification DRC on held-out certification root.

EOF

cat > "$OUT_ROOT/commands.sh" <<EOF
#!/usr/bin/env bash
set -euo pipefail

cd "$ROOT"

# 1. Freeze candidate manifest.
RUN_MAPS="$RUN_MAPS" \\
OUT_ROOT="$OUT_ROOT/construction" \\
PROMPT_DIR="$PROMPT_DIR" \\
CANDIDATE_ROOT="$CANDIDATE_ROOT" \\
CANDIDATE_MANIFEST="$CANDIDATE_MANIFEST" \\
CANDIDATE_MANIFEST_MD="$CANDIDATE_MANIFEST_MD" \\
RUN_FORMAL=false \\
bash "$ROOT/scripts/run_drc_teacher_construction.sh"

# 2. Optional collection. Enable by running this wrapper with COLLECT_BUFFERS=true.
if [[ "$COLLECT_BUFFERS" == "true" ]]; then
  MAPS="$COLLECT_MAPS" \\
  RUN_MAPS="$RUN_MAPS" \\
  TRAIN_COUNT="$TRAIN_COUNT" \\
  TEST_COUNT="$TEST_COUNT" \\
  SEED="$SEED" \\
  COLLECT_CHUNK_SIZE="$COLLECT_CHUNK_SIZE" \\
  OVERWRITE_OUTPUT="$OVERWRITE_OUTPUT" \\
  OUTPUT_ROOT="$BUFFER_ROOT" \\
  AUDIT_OUT="$OUT_ROOT/buffer_collection_audit" \\
  bash "$ROOT/scripts/collect_formal_drc_buffers.sh"
fi

# 3. Split buffers into calibration and certification roots.
"$PY" "$ROOT/scripts/split_drc_buffer_root.py" \\
  --buffer-root "$BUFFER_ROOT" \\
  --maps $RUN_MAPS \\
  --out-root "$SPLIT_ROOT"

# 4. Calibration DRC. This run is used only to derive the fact subset.
RUN_MAPS="$RUN_MAPS" \\
BUFFER_ROOT="$CALIBRATION_ROOT" \\
CANDIDATE_MANIFEST="$CANDIDATE_MANIFEST" \\
OUT_ROOT="$CALIBRATION_OUT" \\
AUDIT_MAX_FILES="$AUDIT_MAX_FILES" \\
MAX_FILES="$MAX_FILES" \\
MAX_TRANSITIONS="$MAX_TRANSITIONS" \\
PROBE_MODEL="$PROBE_MODEL" \\
PROBE_HIDDEN_DIM="$PROBE_HIDDEN_DIM" \\
PROBE_WEIGHT_DECAY="$PROBE_WEIGHT_DECAY" \\
PROBE_EPOCHS="$PROBE_EPOCHS" \\
DECISION_ORACLE="$DECISION_ORACLE" \\
DECISION_LABEL="$DECISION_LABEL" \\
MIN_CONDITIONAL_DECISION_NATS="$MIN_CONDITIONAL_DECISION_NATS" \\
CONDITIONAL_DECISION_MODE="$CONDITIONAL_DECISION_MODE" \\
CONDITIONAL_DECISION_QUANTILE="$CONDITIONAL_DECISION_QUANTILE" \\
MIN_CONDITIONAL_DECISION_SAMPLES="$MIN_CONDITIONAL_DECISION_SAMPLES" \\
MIN_RECEIVER_NECESSITY_RATE="$MIN_RECEIVER_NECESSITY_RATE" \\
SCORE_GAIN_CAP="$SCORE_GAIN_CAP" \\
N_BOOTSTRAP="$N_BOOTSTRAP" \\
N_SIGN_PERMUTATIONS="$N_SIGN_PERMUTATIONS" \\
N_MESSAGE_SHUFFLES="$N_MESSAGE_SHUFFLES" \\
STAT_ALPHA="$STAT_ALPHA" \\
REQUIRE_STAT_SIGNIFICANCE="$REQUIRE_STAT_SIGNIFICANCE" \\
REQUIRE_CONTENT_CONTROL="$REQUIRE_CONTENT_CONTROL" \\
bash "$ROOT/scripts/run_formal_drc_v5.sh"

# 5. Derive fact subset from calibration only.
"$PY" "$ROOT/scripts/make_drc_fact_subset_manifest.py" \\
  --result "$CALIBRATION_OUT/teacher_search" \\
  --out-json "$FACT_SUBSET_MANIFEST" \\
  --out-md "$FACT_SUBSET_MANIFEST_MD"

# 6. Held-out certification DRC.
RUN_MAPS="$RUN_MAPS" \\
BUFFER_ROOT="$CERTIFICATION_ROOT" \\
CANDIDATE_MANIFEST="$CANDIDATE_MANIFEST" \\
FACT_SUBSET_MANIFEST="$FACT_SUBSET_MANIFEST" \\
OUT_ROOT="$CERTIFICATION_OUT" \\
AUDIT_MAX_FILES="$AUDIT_MAX_FILES" \\
MAX_FILES="$MAX_FILES" \\
MAX_TRANSITIONS="$MAX_TRANSITIONS" \\
PROBE_MODEL="$PROBE_MODEL" \\
PROBE_HIDDEN_DIM="$PROBE_HIDDEN_DIM" \\
PROBE_WEIGHT_DECAY="$PROBE_WEIGHT_DECAY" \\
PROBE_EPOCHS="$PROBE_EPOCHS" \\
DECISION_ORACLE="$DECISION_ORACLE" \\
DECISION_LABEL="$DECISION_LABEL" \\
MIN_CONDITIONAL_DECISION_NATS="$MIN_CONDITIONAL_DECISION_NATS" \\
CONDITIONAL_DECISION_MODE="$CONDITIONAL_DECISION_MODE" \\
CONDITIONAL_DECISION_QUANTILE="$CONDITIONAL_DECISION_QUANTILE" \\
MIN_CONDITIONAL_DECISION_SAMPLES="$MIN_CONDITIONAL_DECISION_SAMPLES" \\
MIN_RECEIVER_NECESSITY_RATE="$MIN_RECEIVER_NECESSITY_RATE" \\
SCORE_GAIN_CAP="$SCORE_GAIN_CAP" \\
N_BOOTSTRAP="$N_BOOTSTRAP" \\
N_SIGN_PERMUTATIONS="$N_SIGN_PERMUTATIONS" \\
N_MESSAGE_SHUFFLES="$N_MESSAGE_SHUFFLES" \\
STAT_ALPHA="$STAT_ALPHA" \\
REQUIRE_STAT_SIGNIFICANCE="$REQUIRE_STAT_SIGNIFICANCE" \\
REQUIRE_CONTENT_CONTROL="$REQUIRE_CONTENT_CONTROL" \\
bash "$ROOT/scripts/run_formal_drc_v5.sh"
EOF
chmod +x "$OUT_ROOT/commands.sh"

if [[ "$RUN_MODE" == "dry_run" ]]; then
  cat <<EOF
[DRC-TWO-STAGE] dry run complete.

Plan:
  $OUT_ROOT/README.md
Commands:
  $OUT_ROOT/commands.sh

To split an existing buffer root without running DRC:
  RUN_MODE=split BUFFER_ROOT=<formal_buffer_root> OUT_ROOT="$OUT_ROOT" bash "$ROOT/scripts/run_drc_two_stage_evidence_pipeline.sh"

To execute the full two-stage protocol:
  RUN_MODE=execute BUFFER_ROOT=<formal_buffer_root> OUT_ROOT="$OUT_ROOT" bash "$ROOT/scripts/run_drc_two_stage_evidence_pipeline.sh"
EOF
  exit 0
fi

echo "[DRC-TWO-STAGE] freezing candidate manifest"
RUN_MAPS="$RUN_MAPS" \
OUT_ROOT="$OUT_ROOT/construction" \
PROMPT_DIR="$PROMPT_DIR" \
CANDIDATE_ROOT="$CANDIDATE_ROOT" \
CANDIDATE_MANIFEST="$CANDIDATE_MANIFEST" \
CANDIDATE_MANIFEST_MD="$CANDIDATE_MANIFEST_MD" \
RUN_FORMAL=false \
bash "$ROOT/scripts/run_drc_teacher_construction.sh"

if [[ "$COLLECT_BUFFERS" == "true" ]]; then
  echo "[DRC-TWO-STAGE] collecting formal buffers"
  MAPS="$COLLECT_MAPS" \
  RUN_MAPS="$RUN_MAPS" \
  TRAIN_COUNT="$TRAIN_COUNT" \
  TEST_COUNT="$TEST_COUNT" \
  SEED="$SEED" \
  COLLECT_CHUNK_SIZE="$COLLECT_CHUNK_SIZE" \
  OVERWRITE_OUTPUT="$OVERWRITE_OUTPUT" \
  OUTPUT_ROOT="$BUFFER_ROOT" \
  AUDIT_OUT="$OUT_ROOT/buffer_collection_audit" \
  bash "$ROOT/scripts/collect_formal_drc_buffers.sh"
fi

echo "[DRC-TWO-STAGE] splitting buffers"
"$PY" "$ROOT/scripts/split_drc_buffer_root.py" \
  --buffer-root "$BUFFER_ROOT" \
  --maps $RUN_MAPS \
  --out-root "$SPLIT_ROOT"

if [[ "$RUN_MODE" == "split" ]]; then
  echo "[DRC-TWO-STAGE] split complete: $SPLIT_ROOT"
  exit 0
fi

if [[ "$RUN_MODE" != "execute" ]]; then
  echo "Unknown RUN_MODE=$RUN_MODE; expected dry_run, split, or execute" >&2
  exit 2
fi

echo "[DRC-TWO-STAGE] running calibration DRC"
RUN_MAPS="$RUN_MAPS" \
BUFFER_ROOT="$CALIBRATION_ROOT" \
CANDIDATE_MANIFEST="$CANDIDATE_MANIFEST" \
OUT_ROOT="$CALIBRATION_OUT" \
AUDIT_MAX_FILES="$AUDIT_MAX_FILES" \
MAX_FILES="$MAX_FILES" \
MAX_TRANSITIONS="$MAX_TRANSITIONS" \
PROBE_MODEL="$PROBE_MODEL" \
PROBE_HIDDEN_DIM="$PROBE_HIDDEN_DIM" \
PROBE_WEIGHT_DECAY="$PROBE_WEIGHT_DECAY" \
PROBE_EPOCHS="$PROBE_EPOCHS" \
DECISION_ORACLE="$DECISION_ORACLE" \
DECISION_LABEL="$DECISION_LABEL" \
MIN_CONDITIONAL_DECISION_NATS="$MIN_CONDITIONAL_DECISION_NATS" \
CONDITIONAL_DECISION_MODE="$CONDITIONAL_DECISION_MODE" \
CONDITIONAL_DECISION_QUANTILE="$CONDITIONAL_DECISION_QUANTILE" \
MIN_CONDITIONAL_DECISION_SAMPLES="$MIN_CONDITIONAL_DECISION_SAMPLES" \
MIN_RECEIVER_NECESSITY_RATE="$MIN_RECEIVER_NECESSITY_RATE" \
SCORE_GAIN_CAP="$SCORE_GAIN_CAP" \
N_BOOTSTRAP="$N_BOOTSTRAP" \
N_SIGN_PERMUTATIONS="$N_SIGN_PERMUTATIONS" \
N_MESSAGE_SHUFFLES="$N_MESSAGE_SHUFFLES" \
STAT_ALPHA="$STAT_ALPHA" \
REQUIRE_STAT_SIGNIFICANCE="$REQUIRE_STAT_SIGNIFICANCE" \
REQUIRE_CONTENT_CONTROL="$REQUIRE_CONTENT_CONTROL" \
bash "$ROOT/scripts/run_formal_drc_v5.sh"

echo "[DRC-TWO-STAGE] deriving calibration fact subset"
"$PY" "$ROOT/scripts/make_drc_fact_subset_manifest.py" \
  --result "$CALIBRATION_OUT/teacher_search" \
  --out-json "$FACT_SUBSET_MANIFEST" \
  --out-md "$FACT_SUBSET_MANIFEST_MD"

echo "[DRC-TWO-STAGE] running held-out certification DRC"
RUN_MAPS="$RUN_MAPS" \
BUFFER_ROOT="$CERTIFICATION_ROOT" \
CANDIDATE_MANIFEST="$CANDIDATE_MANIFEST" \
FACT_SUBSET_MANIFEST="$FACT_SUBSET_MANIFEST" \
OUT_ROOT="$CERTIFICATION_OUT" \
AUDIT_MAX_FILES="$AUDIT_MAX_FILES" \
MAX_FILES="$MAX_FILES" \
MAX_TRANSITIONS="$MAX_TRANSITIONS" \
PROBE_MODEL="$PROBE_MODEL" \
PROBE_HIDDEN_DIM="$PROBE_HIDDEN_DIM" \
PROBE_WEIGHT_DECAY="$PROBE_WEIGHT_DECAY" \
PROBE_EPOCHS="$PROBE_EPOCHS" \
DECISION_ORACLE="$DECISION_ORACLE" \
DECISION_LABEL="$DECISION_LABEL" \
MIN_CONDITIONAL_DECISION_NATS="$MIN_CONDITIONAL_DECISION_NATS" \
CONDITIONAL_DECISION_MODE="$CONDITIONAL_DECISION_MODE" \
CONDITIONAL_DECISION_QUANTILE="$CONDITIONAL_DECISION_QUANTILE" \
MIN_CONDITIONAL_DECISION_SAMPLES="$MIN_CONDITIONAL_DECISION_SAMPLES" \
MIN_RECEIVER_NECESSITY_RATE="$MIN_RECEIVER_NECESSITY_RATE" \
SCORE_GAIN_CAP="$SCORE_GAIN_CAP" \
N_BOOTSTRAP="$N_BOOTSTRAP" \
N_SIGN_PERMUTATIONS="$N_SIGN_PERMUTATIONS" \
N_MESSAGE_SHUFFLES="$N_MESSAGE_SHUFFLES" \
STAT_ALPHA="$STAT_ALPHA" \
REQUIRE_STAT_SIGNIFICANCE="$REQUIRE_STAT_SIGNIFICANCE" \
REQUIRE_CONTENT_CONTROL="$REQUIRE_CONTENT_CONTROL" \
bash "$ROOT/scripts/run_formal_drc_v5.sh"

echo "[DRC-TWO-STAGE] complete: $OUT_ROOT"
